/**
 * Workbook runtime bridge — wraps the `workbook-runtime` WASM module in
 * a Connect-shaped client matching the `WorkbookRuntimeService` proto in
 * `proto/workbook/runtime/v1/runtime.proto`.
 *
 * Tier 1 (browser) implementation: dispatches RPC method calls to
 * wasm-bindgen-generated functions in-page. Tier 2 (self-hosted) and Tier 3
 * (managed) plug a different transport in here — over HTTP via Connect-RPC
 * — without touching consumer code. Same method names, same shapes.
 *
 * Sidecar engine (SQLite via `@sqlite.org/sqlite-wasm`) lazy-loads only
 * when a workbook's manifest declares it — wired here, not in the Rust
 * crate.
 *
 * Status (P2.3): Rhai + Polars SQL paths route end-to-end. SQLite
 * sidecar is stubbed with the load shape so consumers can wire it once
 * the Rust runtime is integrated. Streaming responses collapse into a
 * single response array for now (RunCell will become a real ReadableStream
 * in P3 when streaming cells land).
 *
 * DuckDB-WASM was previously wired here as an alternative SQL engine
 * but was deleted (core-0id.7) — Polars-SQL covers the analytical
 * workloads the runtime demos, the SQLite stub remains as the
 * non-Polars roadmap path, and the @duckdb/duckdb-wasm dynamic CDN
 * import was a supply-chain concern. If a consumer needs DuckDB,
 * they wire it in their own runtime client.
 */

// Minimal Cell + Environment + CellOutput shapes that match the proto in
// `proto/workbook/v1/workbook.proto`. Hand-rolled until P2.5 wires up
// generated bindings via buf. Once that lands, replace these with the
// generated types and drop these declarations.

export type CellLanguage =
  | "rhai"
  | "polars"
  | "sqlite"
  | "candle-inference"
  | "linfa-train"
  | "wasm-fn"
  | "chat";

export interface Cell {
  id: string;
  language: CellLanguage;
  source?: string;
  spec?: unknown;
  dependsOn?: string[];
  provides?: string[];
}

export interface Environment {
  bundleVersion?: string;
  contractVersion?: string;
  features?: string[];
}

/**
 * Cell output. Mirrors the discriminated union in src/outputs.rs.
 * Variants serialize as snake_case via serde's `rename_all = "snake_case"`:
 *   { kind: "text",   content, mime_type? }
 *   { kind: "image",  content (base64), mime_type }
 *   { kind: "table",  sql_table, row_count? }
 *   { kind: "error",  message, traceback? }
 *   { kind: "stream", content }
 */
export type CellOutput =
  | { kind: "text"; content: string; mime_type?: string }
  | { kind: "image"; content: string; mime_type: string }
  | { kind: "table"; sql_table: string; row_count?: number }
  | { kind: "error"; message: string; traceback?: string }
  | { kind: "stream"; content: string };

/**
 * Init payload. The Rust runtime side accepts the same shape via
 * wasm-bindgen serde — `workbook_slug` + `environment`.
 */
export interface InitRuntimeRequest {
  workbookSlug: string;
  environment: Environment;
}

export interface InitRuntimeResponse {
  runtimeId: string;
  initMs: number;
  warmStart: boolean;
}

export interface RunCellRequest {
  runtimeId: string;
  cell: Cell;
  params?: Record<string, unknown>;
}

export interface RunCellResponse {
  outputs: CellOutput[];
}

export interface BuildInfo {
  name: string;
  version: string;
  contract_version: string;
  features: string[];
  cold_start_ms?: number;
}

/**
 * Loader contract — the consumer hands us a function that returns the
 * wasm-bindgen module's exports. This keeps the bridge agnostic to where
 * the wasm comes from (local pkg/ in dev, CDN URL in prod, inlined in
 * portable export mode).
 */
export type WasmLoader = () => Promise<WorkbookRuntimeWasm>;

/** Subset of wasm-bindgen exports we depend on. Generated by wasm-pack. */
export interface WorkbookRuntimeWasm {
  /** Default-exported init function from wasm-bindgen — fetches the .wasm. */
  default: (input?: unknown) => Promise<unknown>;
  build_info: () => BuildInfo;
  initRuntime: (req: { workbook_slug: string; environment: Environment }) => InitRuntimeResponse;
  runRhai?: (source: string, params?: unknown) => CellOutput[];
  runPolarsSql?: (sql: string, csv: string) => CellOutput[];
  runChart?: (spec_json: string) => CellOutput[];
  candleSmokeTest?: () => CellOutput[];
  linfaSmokeTest?: () => CellOutput[];
  pauseRuntime?: (req: { runtime_id: string }) => null;
  destroyRuntime?: (req: { runtime_id: string }) => null;
}

export interface RuntimeClient {
  initRuntime(req: InitRuntimeRequest): Promise<InitRuntimeResponse>;
  runCell(req: RunCellRequest): Promise<RunCellResponse>;
  pauseRuntime(runtimeId: string): Promise<void>;
  destroyRuntime(runtimeId: string): Promise<void>;
  buildInfo(): Promise<BuildInfo>;
}

export interface RuntimeClientOptions {
  /**
   * Load the workbook-runtime WASM module. In a Vite/Webpack project that
   * has the package as a dep, this is usually:
   *
   *   () => import("workbook-runtime")
   *
   * For portable export mode, the inlined runtime supplies its own loader.
   */
  loadWasm: WasmLoader;
  /**
   * Optional LLM client used to dispatch `chat` cells. When unset, chat
   * cells fail with an explanatory error. Hosts wire this via
   * `createBrowserLlmClient(...)` (Tier 1) or one of the Tier 2/3
   * transports.
   */
  llmClient?: import("./llmClient").LlmClient;
}

/**
 * Create a Tier 1 (browser, in-page WASM) runtime client. The client
 * lazy-initializes the wasm module on first method call — first hit takes
 * the wasm fetch + instantiate cost (~30-200 ms typically), subsequent
 * calls are direct function calls.
 */
export function createRuntimeClient(opts: RuntimeClientOptions): RuntimeClient {
  let wasmPromise: Promise<WorkbookRuntimeWasm> | null = null;

  function ensureWasm(): Promise<WorkbookRuntimeWasm> {
    if (!wasmPromise) {
      wasmPromise = (async () => {
        const mod = await opts.loadWasm();
        await mod.default();
        return mod;
      })();
    }
    return wasmPromise;
  }

  return {
    async initRuntime(req) {
      const wasm = await ensureWasm();
      return wasm.initRuntime({
        workbook_slug: req.workbookSlug,
        environment: req.environment,
      });
    },

    async runCell(req) {
      const wasm = await ensureWasm();
      const lang = req.cell.language;

      if (lang === "rhai") {
        if (!wasm.runRhai) throw new Error("runtime built without rhai-glue feature");
        const outputs = wasm.runRhai(req.cell.source ?? "", req.params ?? {});
        return { outputs };
      }

      if (lang === "polars") {
        if (!wasm.runPolarsSql) throw new Error("runtime built without polars-frames feature");
        const sql = req.cell.source ?? "";
        const csv = (req.params?.csv as string | undefined) ?? "";
        const outputs = wasm.runPolarsSql(sql, csv);
        return { outputs };
      }

      if (lang === "sqlite") {
        // P2.5+: lazy-load @sqlite.org/sqlite-wasm here, run query, return
        // outputs. Stubbed today — see docs/RUST_RUNTIME.md.
        throw new Error("sqlite cell dispatcher not yet wired (P2.5)");
      }

      // duckdb dispatch removed (core-0id.7). Polars-SQL covers analytical
      // workloads; SQLite stays the non-Polars roadmap (above).

      if (lang === "chat") {
        if (!opts.llmClient) {
          throw new Error(
            "chat cells require an llmClient — pass one to createRuntimeClient",
          );
        }
        const params = (req.params ?? {}) as Record<string, unknown>;
        const userMessage = String(params.message ?? params.user ?? "");
        const history = Array.isArray(params.history) ? (params.history as unknown[]) : [];
        const messages: import("./llmClient").ChatMessage[] = [];
        if (req.cell.source) {
          messages.push({ role: "system", content: req.cell.source });
        }
        for (const m of history) {
          if (m && typeof m === "object") {
            messages.push(m as import("./llmClient").ChatMessage);
          }
        }
        if (userMessage) messages.push({ role: "user", content: userMessage });

        const model =
          (params.model as string | undefined) ??
          (req.cell.spec as { model?: string } | undefined)?.model ??
          "openai/gpt-4o-mini";

        const stream = opts.llmClient.generateChat({
          model,
          messages,
          temperature: typeof params.temperature === "number" ? params.temperature : undefined,
          maxOutputTokens:
            typeof params.maxOutputTokens === "number" ? params.maxOutputTokens : undefined,
        });

        const outputs: CellOutput[] = [];
        for await (const ev of stream) {
          if (ev.kind === "delta") {
            outputs.push({ kind: "stream", content: ev.text });
          } else if (ev.kind === "done") {
            if (ev.stopReason === "error") {
              outputs.push({ kind: "error", message: ev.errorMessage ?? "llm error" });
            } else {
              outputs.push({
                kind: "text",
                content: ev.finalText,
                mime_type: "text/plain",
              });
            }
          }
        }
        return { outputs };
      }

      if (lang === "candle-inference") {
        // P4.1: scaffold dispatch. Today the smoke-test path proves
        // Candle is alive in the WASM bundle. Real model loading goes
        // through @workbook/runtime/modelArtifactResolver and lands as
        // P4.1+ work — for now this confirms the dispatcher is wired.
        if (!wasm.candleSmokeTest) {
          throw new Error("runtime built without candle feature");
        }
        const outputs = wasm.candleSmokeTest();
        return { outputs };
      }

      if (lang === "linfa-train") {
        // P4.4: scaffold dispatch. Smoke-test path fits a 1-feature
        // linear regression to prove Linfa is alive. Real dataset-driven
        // training (with the workbook data layer) lands incrementally.
        if (!wasm.linfaSmokeTest) {
          throw new Error("runtime built without linfa feature");
        }
        const outputs = wasm.linfaSmokeTest();
        return { outputs };
      }

      throw new Error(`unsupported cell language: ${lang}`);
    },

    async pauseRuntime(runtimeId) {
      const wasm = await ensureWasm();
      wasm.pauseRuntime?.({ runtime_id: runtimeId });
    },

    async destroyRuntime(runtimeId) {
      const wasm = await ensureWasm();
      wasm.destroyRuntime?.({ runtime_id: runtimeId });
    },

    async buildInfo() {
      const wasm = await ensureWasm();
      return wasm.build_info();
    },
  };
}
