/**
 * Workbook runtime bridge — wraps the `workbook-runtime` WASM module in
 * a Connect-shaped client matching the `WorkbookRuntimeService` proto in
 * `proto/workbook/runtime/v1/runtime.proto`.
 *
 * Tier 1 (browser) implementation: dispatches RPC method calls to
 * wasm-bindgen-generated functions in-page. Tier 2 (self-hosted) and Tier 3
 * (managed) plug a different transport in here — over HTTP via Connect-RPC
 * — without touching consumer code. Same method names, same shapes.
 *
 * Sidecar engines (SQLite via `@sqlite.org/sqlite-wasm`, DuckDB via
 * `@duckdb/duckdb-wasm`) lazy-load only when a workbook's manifest declares
 * them — wired here, not in the Rust crate.
 *
 * Status (P2.3): Rhai + Polars SQL paths route end-to-end. SQLite/DuckDB
 * sidecars are stubbed with the load shape so consumers can wire them once
 * the Rust runtime is integrated. Streaming responses collapse into a
 * single response array for now (RunCell will become a real ReadableStream
 * in P3 when streaming cells land).
 */

// Minimal Cell + Environment + CellOutput shapes that match the proto in
// `proto/workbook/v1/workbook.proto`. Hand-rolled until P2.5 wires up
// generated bindings via buf. Once that lands, replace these with the
// generated types and drop these declarations.

export type CellLanguage =
  | "rhai"
  | "polars"
  | "sqlite"
  | "duckdb"
  | "candle-inference"
  | "linfa-train"
  | "wasm-fn";

export interface Cell {
  id: string;
  language: CellLanguage;
  source?: string;
  spec?: unknown;
  dependsOn?: string[];
  provides?: string[];
}

export interface Environment {
  bundleVersion?: string;
  contractVersion?: string;
  features?: string[];
}

/**
 * Cell output. Mirrors the discriminated union in src/outputs.rs.
 * Variants serialize as snake_case via serde's `rename_all = "snake_case"`:
 *   { kind: "text",   content, mime_type? }
 *   { kind: "image",  content (base64), mime_type }
 *   { kind: "table",  sql_table, row_count? }
 *   { kind: "error",  message, traceback? }
 *   { kind: "stream", content }
 */
export type CellOutput =
  | { kind: "text"; content: string; mime_type?: string }
  | { kind: "image"; content: string; mime_type: string }
  | { kind: "table"; sql_table: string; row_count?: number }
  | { kind: "error"; message: string; traceback?: string }
  | { kind: "stream"; content: string };

/**
 * Init payload. The Rust runtime side accepts the same shape via
 * wasm-bindgen serde — `workbook_slug` + `environment`.
 */
export interface InitRuntimeRequest {
  workbookSlug: string;
  environment: Environment;
}

export interface InitRuntimeResponse {
  runtimeId: string;
  initMs: number;
  warmStart: boolean;
}

export interface RunCellRequest {
  runtimeId: string;
  cell: Cell;
  params?: Record<string, unknown>;
}

export interface RunCellResponse {
  outputs: CellOutput[];
}

export interface BuildInfo {
  name: string;
  version: string;
  contract_version: string;
  features: string[];
  cold_start_ms?: number;
}

/**
 * Loader contract — the consumer hands us a function that returns the
 * wasm-bindgen module's exports. This keeps the bridge agnostic to where
 * the wasm comes from (local pkg/ in dev, CDN URL in prod, inlined in
 * portable export mode).
 */
export type WasmLoader = () => Promise<WorkbookRuntimeWasm>;

/** Subset of wasm-bindgen exports we depend on. Generated by wasm-pack. */
export interface WorkbookRuntimeWasm {
  /** Default-exported init function from wasm-bindgen — fetches the .wasm. */
  default: (input?: unknown) => Promise<unknown>;
  build_info: () => BuildInfo;
  initRuntime: (req: { workbook_slug: string; environment: Environment }) => InitRuntimeResponse;
  runRhai?: (source: string, params?: unknown) => CellOutput[];
  runPolarsSql?: (sql: string, csv: string) => CellOutput[];
  runChart?: (spec_json: string) => CellOutput[];
  candleSmokeTest?: () => CellOutput[];
  linfaSmokeTest?: () => CellOutput[];
  pauseRuntime?: (req: { runtime_id: string }) => null;
  destroyRuntime?: (req: { runtime_id: string }) => null;
}

export interface RuntimeClient {
  initRuntime(req: InitRuntimeRequest): Promise<InitRuntimeResponse>;
  runCell(req: RunCellRequest): Promise<RunCellResponse>;
  pauseRuntime(runtimeId: string): Promise<void>;
  destroyRuntime(runtimeId: string): Promise<void>;
  buildInfo(): Promise<BuildInfo>;
}

export interface RuntimeClientOptions {
  /**
   * Load the workbook-runtime WASM module. In a Vite/Webpack project that
   * has the package as a dep, this is usually:
   *
   *   () => import("workbook-runtime")
   *
   * For portable export mode, the inlined runtime supplies its own loader.
   */
  loadWasm: WasmLoader;
}

/**
 * Create a Tier 1 (browser, in-page WASM) runtime client. The client
 * lazy-initializes the wasm module on first method call — first hit takes
 * the wasm fetch + instantiate cost (~30-200 ms typically), subsequent
 * calls are direct function calls.
 */
export function createRuntimeClient(opts: RuntimeClientOptions): RuntimeClient {
  let wasmPromise: Promise<WorkbookRuntimeWasm> | null = null;

  function ensureWasm(): Promise<WorkbookRuntimeWasm> {
    if (!wasmPromise) {
      wasmPromise = (async () => {
        const mod = await opts.loadWasm();
        await mod.default();
        return mod;
      })();
    }
    return wasmPromise;
  }

  return {
    async initRuntime(req) {
      const wasm = await ensureWasm();
      return wasm.initRuntime({
        workbook_slug: req.workbookSlug,
        environment: req.environment,
      });
    },

    async runCell(req) {
      const wasm = await ensureWasm();
      const lang = req.cell.language;

      if (lang === "rhai") {
        if (!wasm.runRhai) throw new Error("runtime built without rhai-glue feature");
        const outputs = wasm.runRhai(req.cell.source ?? "", req.params ?? {});
        return { outputs };
      }

      if (lang === "polars") {
        if (!wasm.runPolarsSql) throw new Error("runtime built without polars-frames feature");
        const sql = req.cell.source ?? "";
        const csv = (req.params?.csv as string | undefined) ?? "";
        const outputs = wasm.runPolarsSql(sql, csv);
        return { outputs };
      }

      if (lang === "sqlite") {
        // P2.5+: lazy-load @sqlite.org/sqlite-wasm here, run query, return
        // outputs. Stubbed today — see docs/RUST_RUNTIME.md.
        throw new Error("sqlite cell dispatcher not yet wired (P2.5)");
      }

      if (lang === "duckdb") {
        // P3.1: lazy-load @duckdb/duckdb-wasm sidecar. The DuckDB chunk
        // (~7 MB) only fetches when a workbook actually runs a duckdb
        // cell; workbooks using only Polars/Rhai/charts never pay for it.
        const { runDuckdbSql } = await import("./duckdbSidecar");
        const sql = req.cell.source ?? "";
        const csv = (req.params?.csv as string | undefined) ?? "";
        const outputs = await runDuckdbSql(sql, csv);
        return { outputs };
      }

      if (lang === "candle-inference") {
        // P4.1: scaffold dispatch. Today the smoke-test path proves
        // Candle is alive in the WASM bundle. Real model loading goes
        // through @workbook/runtime/modelArtifactResolver and lands as
        // P4.1+ work — for now this confirms the dispatcher is wired.
        if (!wasm.candleSmokeTest) {
          throw new Error("runtime built without candle feature");
        }
        const outputs = wasm.candleSmokeTest();
        return { outputs };
      }

      if (lang === "linfa-train") {
        // P4.4: scaffold dispatch. Smoke-test path fits a 1-feature
        // linear regression to prove Linfa is alive. Real dataset-driven
        // training (with the workbook data layer) lands incrementally.
        if (!wasm.linfaSmokeTest) {
          throw new Error("runtime built without linfa feature");
        }
        const outputs = wasm.linfaSmokeTest();
        return { outputs };
      }

      throw new Error(`unsupported cell language: ${lang}`);
    },

    async pauseRuntime(runtimeId) {
      const wasm = await ensureWasm();
      wasm.pauseRuntime?.({ runtime_id: runtimeId });
    },

    async destroyRuntime(runtimeId) {
      const wasm = await ensureWasm();
      wasm.destroyRuntime?.({ runtime_id: runtimeId });
    },

    async buildInfo() {
      const wasm = await ensureWasm();
      return wasm.build_info();
    },
  };
}
