/**
 * Workbook runtime bridge — wraps the `workbook-runtime` WASM module in
 * a Connect-shaped client matching the `WorkbookRuntimeService` proto in
 * `proto/workbook/runtime/v1/runtime.proto`.
 *
 * Tier 1 (browser) implementation: dispatches RPC method calls to
 * wasm-bindgen-generated functions in-page. Tier 2 (self-hosted) and Tier 3
 * (managed) plug a different transport in here — over HTTP via Connect-RPC
 * — without touching consumer code. Same method names, same shapes.
 *
 * Sidecar engine (SQLite via `@sqlite.org/sqlite-wasm`) lazy-loads only
 * when a workbook's manifest declares it — wired here, not in the Rust
 * crate.
 *
 * Status (P2.3): Rhai + Polars SQL paths route end-to-end. SQLite
 * sidecar is stubbed with the load shape so consumers can wire it once
 * the Rust runtime is integrated. Streaming responses collapse into a
 * single response array for now (RunCell will become a real ReadableStream
 * in P3 when streaming cells land).
 *
 * DuckDB-WASM was previously wired here as an alternative SQL engine
 * but was deleted (core-0id.7) — Polars-SQL covers the analytical
 * workloads the runtime demos, the SQLite stub remains as the
 * non-Polars roadmap path, and the @duckdb/duckdb-wasm dynamic CDN
 * import was a supply-chain concern. If a consumer needs DuckDB,
 * they wire it in their own runtime client.
 */

import {
  createSqliteDispatcher,
  type SqliteDispatcher,
} from "./sqliteSidecar";

// Minimal Cell + Environment + CellOutput shapes that match the proto in
// `proto/workbook/v1/workbook.proto`. Hand-rolled until P2.5 wires up
// generated bindings via buf. Once that lands, replace these with the
// generated types and drop these declarations.

export type CellLanguage =
  | "rhai"
  | "polars"
  | "sqlite"
  | "candle-inference"
  | "linfa-train"
  | "wasm-fn"
  | "chat";

export interface Cell {
  id: string;
  language: CellLanguage;
  source?: string;
  spec?: unknown;
  dependsOn?: string[];
  provides?: string[];
}

export interface Environment {
  bundleVersion?: string;
  contractVersion?: string;
  features?: string[];
}

/**
 * Cell output. Mirrors the discriminated union in src/outputs.rs.
 * Variants serialize as snake_case via serde's `rename_all = "snake_case"`:
 *   { kind: "text",   content, mime_type? }
 *   { kind: "image",  content (base64), mime_type }
 *   { kind: "table",  sql_table, row_count? }
 *   { kind: "error",  message, traceback? }
 *   { kind: "stream", content }
 */
export type CellOutput =
  | { kind: "text"; content: string; mime_type?: string }
  | { kind: "image"; content: string; mime_type: string }
  | { kind: "table"; sql_table: string; row_count?: number }
  | { kind: "error"; message: string; traceback?: string }
  | { kind: "stream"; content: string };

/**
 * Init payload. The Rust runtime side accepts the same shape via
 * wasm-bindgen serde — `workbook_slug` + `environment`.
 */
export interface InitRuntimeRequest {
  workbookSlug: string;
  environment: Environment;
}

export interface InitRuntimeResponse {
  runtimeId: string;
  initMs: number;
  warmStart: boolean;
}

export interface RunCellRequest {
  runtimeId: string;
  cell: Cell;
  params?: Record<string, unknown>;
  /**
   * Memory tables available to this cell. Keyed by memory id; value
   * is the current Arrow IPC stream bytes for that table. Polars-SQL
   * cells get these registered as table sources matching the id.
   * Cells with no `reads=` references to memory ids see an empty map.
   */
  memoryTables?: Record<string, Uint8Array>;
}

export interface RunCellResponse {
  outputs: CellOutput[];
}

export interface BuildInfo {
  name: string;
  version: string;
  contract_version: string;
  features: string[];
  cold_start_ms?: number;
}

/**
 * Loader contract — the consumer hands us a function that returns the
 * wasm-bindgen module's exports. This keeps the bridge agnostic to where
 * the wasm comes from (local pkg/ in dev, CDN URL in prod, inlined in
 * portable export mode).
 */
export type WasmLoader = () => Promise<WorkbookRuntimeWasm>;

/** Subset of wasm-bindgen exports we depend on. Generated by wasm-pack. */
export interface WorkbookRuntimeWasm {
  /** Default-exported init function from wasm-bindgen — fetches the .wasm. */
  default: (input?: unknown) => Promise<unknown>;
  build_info: () => BuildInfo;
  initRuntime: (req: { workbook_slug: string; environment: Environment }) => InitRuntimeResponse;
  runRhai?: (source: string, params?: unknown) => CellOutput[];
  runPolarsSql?: (sql: string, csv: string) => CellOutput[];
  /**
   * Run Polars-SQL with one or more registered Arrow IPC tables.
   * `tables` is a JSON object mapping table name → Uint8Array of
   * Arrow IPC stream bytes. Cells reference tables by name in their
   * SQL source. Lands once the Rust crate's IPC feature is wired
   * through wasm-bindgen.
   */
  runPolarsSqlIpc?: (sql: string, tables: Record<string, Uint8Array>) => CellOutput[];
  /**
   * Concatenate two Arrow IPC streams under a single schema header
   * + EOS, validating schema compatibility. Used by appendMemory
   * to produce a well-formed stream — naive byte concat would
   * truncate at the first EOS marker. Throws if schemas differ.
   */
  appendArrowIpc?: (existing: Uint8Array, new_batch: Uint8Array) => Uint8Array;
  /**
   * Generic JSON-to-Arrow encoder. `schemaJson` describes columns
   * (`{fields:[{name,type:"utf8"|"i64",nullable?}]}`); `rowsJson` is
   * an array of objects with matching keys. Returns a complete Arrow
   * IPC stream containing one batch. Lets host code emit memory
   * batches without an Arrow JS dep.
   */
  arrowEncodeJsonRows?: (schemaJson: string, rowsJson: string) => Uint8Array;
  /** Inverse of arrowEncodeJsonRows. Walks every batch in the IPC
   *  stream, returns rows as a JSON-encoded array string. */
  arrowDecodeToJsonRows?: (bytes: Uint8Array) => string;
  // ─── Phase E: Rust-side age decrypt + handle registry ─────────
  // Plaintext stays in WASM linear memory; JS gets opaque handle
  // IDs and uses them via the handle-aware paths below.
  /** Decrypt an age envelope; plaintext stored under a fresh handle
   *  in Rust-side registry. Returns the handle id. */
  ageDecryptToHandle?: (ciphertext: Uint8Array, passphrase: string) => number;
  /** Compat path — decrypt + return plaintext to JS. Used by code
   *  that hasn't migrated to handles. Crosses the boundary. */
  ageDecryptToBytes?: (ciphertext: Uint8Array, passphrase: string) => Uint8Array;
  /** Phase D — decrypt with X25519 identities (`AGE-SECRET-KEY-1...`
   *  strings). Identities are tried in order; first match unwraps.
   *  Plaintext stays in linear memory like ageDecryptToHandle. */
  ageDecryptWithIdentitiesToHandle?: (
    ciphertext: Uint8Array,
    identities: string[],
  ) => number;
  /** Free the bytes at a handle. Returns true if slot was occupied. */
  handleDispose?: (id: number) => boolean;
  /** Plaintext byte-length at a handle; 0 if disposed/unknown. */
  handleSize?: (id: number) => number;
  /** Escape hatch — copy bytes out to JS. Use sparingly; defeats
   *  the isolation property. */
  handleExport?: (id: number) => Uint8Array;
  /** Lowercase-hex SHA-256 of the plaintext at this handle. Used
   *  to verify the digest matches the `<wb-data sha256="...">`
   *  attribute without exporting bytes — the integrity check
   *  stays Rust-side. Empty string for unknown handles. */
  handleSha256?: (id: number) => string;
  /** Polars-SQL over handle-addressed Arrow IPC tables. Bytes never
   *  cross to JS. Same shape as runPolarsSqlIpc but values are
   *  handle ids instead of Uint8Arrays. */
  runPolarsSqlIpcHandles?: (
    sql: string,
    tableHandles: Record<string, number>,
  ) => CellOutput[];
  // ----- Prolly Tree (<wb-history>) primitives -----
  /** Initialize an empty history with a single root commit. */
  prollyInit?: (message: string) => Uint8Array;
  /** Read HEAD commit hash (hex). */
  prollyHead?: (serialized: Uint8Array) => string;
  /** Read value at key from current HEAD's leaf. Returns Uint8Array | null. */
  prollyGet?: (serialized: Uint8Array, key: string) => Uint8Array | null;
  /** List utf-8 keys in current HEAD's leaf. */
  prollyKeys?: (serialized: Uint8Array) => string[];
  /** Set key=value, commit, return new serialized history bytes. */
  prollySet?: (serialized: Uint8Array, key: string, value: Uint8Array, message: string) => Uint8Array;
  /** Remove key, commit, return new serialized history bytes. */
  prollyDelete?: (serialized: Uint8Array, key: string, message: string) => Uint8Array;
  /** Walk parent chain from HEAD, return array of commit info. */
  prollyLog?: (serialized: Uint8Array) => Array<{
    hash: string;
    parent: string | null;
    root: string;
    timestamp_ms: number;
    message: string;
  }>;
  /** Materialize the leaf at a past commit. Returns [key, value][]. */
  prollyCheckout?: (serialized: Uint8Array, commit_hash_hex: string) => Array<[string, Uint8Array]>;
  /** Truncate the chain so HEAD = target_hex, dropping commits after
   *  target. Used by cursor-based undo: editing while behind HEAD
   *  truncates first so the new commit's parent is the cursor. */
  prollyTruncateTo?: (serialized: Uint8Array, target_hex: string) => Uint8Array;
  runChart?: (spec_json: string) => CellOutput[];
  candleSmokeTest?: () => CellOutput[];
  linfaSmokeTest?: () => CellOutput[];
  pauseRuntime?: (req: { runtime_id: string }) => null;
  destroyRuntime?: (req: { runtime_id: string }) => null;
}

export interface RuntimeClient {
  initRuntime(req: InitRuntimeRequest): Promise<InitRuntimeResponse>;
  runCell(req: RunCellRequest): Promise<RunCellResponse>;
  pauseRuntime(runtimeId: string): Promise<void>;
  destroyRuntime(runtimeId: string): Promise<void>;
  buildInfo(): Promise<BuildInfo>;
  /**
   * Register an Arrow IPC stream as a queryable table named `id`.
   * Polars-SQL cells whose `reads=` references this id will see it
   * as a registered table source. Called once per memory block at
   * mount; later overwritten by appendMemory after each write.
   */
  registerMemory?(id: string, bytes: Uint8Array): Promise<void>;
  /**
   * Append rows to a registered memory table. `rows` is encoded as
   * an Arrow IPC stream containing one or more record batches that
   * the runtime concatenates onto the existing buffer in WASM
   * linear memory. Returns the new aggregate sha256 + byte length
   * so the host can persist on save.
   */
  appendMemory?(id: string, rows: Uint8Array): Promise<{ sha256: string; bytes: number }>;
  /**
   * Export the current state of a memory table as Arrow IPC bytes
   * for re-saving into the workbook HTML.
   */
  exportMemory?(id: string): Promise<Uint8Array>;
  /**
   * Register a CRDT doc handle by id. Called once per <wb-doc> at
   * mount; subsequent docMutate calls dispatch by id.
   */
  registerDoc?(id: string, handle: import("./loroSidecar").LoroDocHandle): Promise<void>;
  /**
   * Apply structured ops to a registered doc as a single op-log
   * entry. Returns the new snapshot bytes + sha256 + length so the
   * host can persist on save.
   */
  docMutate?(
    id: string,
    ops: import("./loroSidecar").DocOp[],
  ): Promise<{ sha256: string; bytes: number; snapshot: Uint8Array }>;
  /** Export the current state of a doc as snapshot bytes for save. */
  exportDoc?(id: string): Promise<Uint8Array>;
  /** Read the current JSON projection of a doc. */
  readDoc?(id: string): Promise<unknown>;
  /**
   * Retrieve a registered doc's live handle. The handle exposes Loro's
   * full mutation API; useful for the SDK's useDoc() hook so authors
   * can write `doc.getText("body").insert(...)` style code without
   * round-tripping every change through docMutate.
   *
   * Returns undefined if no doc with `id` is registered. Callers should
   * null-check; the runtime registers docs at mount time, so this is
   * available once the workbook has booted.
   */
  getDocHandle?(id: string): import("./loroSidecar").LoroDocHandle | undefined;
  /**
   * List the ids of all registered <wb-doc> handles. Used by the wb.*
   * storage SDK's resolver to find a "default doc" when authors call
   * `wb.text("composition")` without specifying a doc id explicitly.
   * Returns an empty array if no docs are registered.
   */
  listDocIds?(): string[];
}

export interface RuntimeClientOptions {
  /**
   * Load the workbook-runtime WASM module. In a Vite/Webpack project that
   * has the package as a dep, this is usually:
   *
   *   () => import("workbook-runtime")
   *
   * For portable export mode, the inlined runtime supplies its own loader.
   */
  loadWasm: WasmLoader;
  /**
   * Optional LLM client used to dispatch `chat` cells. When unset, chat
   * cells fail with an explanatory error. Hosts wire this via
   * `createBrowserLlmClient(...)` (Tier 1) or one of the Tier 2/3
   * transports.
   */
  llmClient?: import("./llmClient").LlmClient;
}

/**
 * Create a Tier 1 (browser, in-page WASM) runtime client. The client
 * lazy-initializes the wasm module on first method call — first hit takes
 * the wasm fetch + instantiate cost (~30-200 ms typically), subsequent
 * calls are direct function calls.
 */
export function createRuntimeClient(opts: RuntimeClientOptions): RuntimeClient {
  let wasmPromise: Promise<WorkbookRuntimeWasm> | null = null;
  // Lazy SQLite sidecar — only constructed when a sqlite cell dispatches.
  // We don't import the dispatcher module eagerly so workbooks that
  // never use sqlite never pay the @sqlite.org/sqlite-wasm load cost.
  let sqlite: SqliteDispatcher | null = null;
  // Memory tables — Arrow IPC stream bytes keyed by memory id. The
  // current implementation holds bytes in JS linear memory and
  // concatenates streams on append (Arrow IPC is append-native at
  // the format level). When the Rust runtime exposes
  // registerArrowTable / appendArrowBatch / exportArrowTable
  // wasm-bindgen exports, this becomes a thin shim that delegates
  // to WASM linear memory; the JS-side contract is unchanged.
  const memoryBuffers = new Map<string, Uint8Array>();
  // CRDT doc handles registered at mount. The handle owns the live
  // LoroDoc; the client just routes mutate / export / read calls to it.
  const docHandles = new Map<string, import("./loroSidecar").LoroDocHandle>();

  function ensureWasm(): Promise<WorkbookRuntimeWasm> {
    if (!wasmPromise) {
      wasmPromise = (async () => {
        const mod = await opts.loadWasm();
        await mod.default();
        return mod;
      })();
    }
    return wasmPromise;
  }

  return {
    async initRuntime(req) {
      const wasm = await ensureWasm();
      return wasm.initRuntime({
        workbook_slug: req.workbookSlug,
        environment: req.environment,
      });
    },

    async runCell(req) {
      const wasm = await ensureWasm();
      const lang = req.cell.language;

      if (lang === "rhai") {
        if (!wasm.runRhai) throw new Error("runtime built without rhai-glue feature");
        const outputs = wasm.runRhai(req.cell.source ?? "", req.params ?? {});
        return { outputs };
      }

      if (lang === "polars") {
        if (!wasm.runPolarsSql) throw new Error("runtime built without polars-frames feature");
        const sql = req.cell.source ?? "";

        // Memory tables (Arrow IPC) take precedence over CSV params
        // when the cell's `reads=` references a registered memory id.
        // Each referenced memory becomes a table available to the SQL
        // by its id name.
        const memoryTables: Record<string, Uint8Array> = {};
        if (req.memoryTables && req.cell.dependsOn) {
          for (const dep of req.cell.dependsOn) {
            const t = req.memoryTables[dep];
            if (t instanceof Uint8Array) memoryTables[dep] = t;
          }
        }

        if (Object.keys(memoryTables).length > 0) {
          if (!wasm.runPolarsSqlIpc) {
            throw new Error(
              "polars cell references a <wb-memory> table but the runtime " +
                "build does not expose runPolarsSqlIpc — rebuild runtime-wasm " +
                "with the `ipc` polars feature and the wasm-bindgen export wired",
            );
          }
          const outputs = wasm.runPolarsSqlIpc(sql, memoryTables);
          return { outputs };
        }

        // CSV fallback (the existing path):
        //   1. Explicit `params.csv` (legacy: `<wb-input name="csv">`).
        //   2. The first `reads=` ref whose param is a string —
        //      i.e. a `<wb-data mime="text/csv">` referenced by id.
        let csv = (req.params?.csv as string | undefined) ?? "";
        if (!csv && req.params && req.cell.dependsOn) {
          for (const dep of req.cell.dependsOn) {
            const v = req.params[dep];
            if (typeof v === "string" && v.length > 0) {
              csv = v;
              break;
            }
          }
        }
        const outputs = wasm.runPolarsSql(sql, csv);
        return { outputs };
      }

      if (lang === "sqlite") {
        // SQLite is a JS-side sidecar (@sqlite.org/sqlite-wasm), not a
        // Rust-bundled feature. We pull the database bytes from a
        // `<wb-data mime="application/x-sqlite3">` referenced via reads=.
        let dataId: string | null = null;
        let dbBytes: Uint8Array | null = null;
        if (req.params && req.cell.dependsOn) {
          for (const dep of req.cell.dependsOn) {
            const v = req.params[dep];
            if (v instanceof Uint8Array) {
              dataId = dep;
              dbBytes = v;
              break;
            }
          }
        }
        if (!dbBytes || !dataId) {
          throw new Error(
            "sqlite cells require a `reads=` reference to a " +
              "<wb-data mime=\"application/x-sqlite3\"> block holding the " +
              "database bytes",
          );
        }
        if (!sqlite) sqlite = createSqliteDispatcher();
        const outputs = await sqlite.exec({
          workbookSlug: req.runtimeId || "default",
          dataId,
          dbBytes,
          sql: req.cell.source ?? "",
        });
        return { outputs };
      }

      // duckdb dispatch removed (core-0id.7). Polars-SQL covers analytical
      // workloads; SQLite stays the non-Polars roadmap (above).

      if (lang === "chat") {
        if (!opts.llmClient) {
          throw new Error(
            "chat cells require an llmClient — pass one to createRuntimeClient",
          );
        }
        const params = (req.params ?? {}) as Record<string, unknown>;
        const userMessage = String(params.message ?? params.user ?? "");
        const history = Array.isArray(params.history) ? (params.history as unknown[]) : [];
        const messages: import("./llmClient").ChatMessage[] = [];
        if (req.cell.source) {
          messages.push({ role: "system", content: req.cell.source });
        }
        for (const m of history) {
          if (m && typeof m === "object") {
            messages.push(m as import("./llmClient").ChatMessage);
          }
        }
        if (userMessage) messages.push({ role: "user", content: userMessage });

        const model =
          (params.model as string | undefined) ??
          (req.cell.spec as { model?: string } | undefined)?.model ??
          "openai/gpt-4o-mini";

        const stream = opts.llmClient.generateChat({
          model,
          messages,
          temperature: typeof params.temperature === "number" ? params.temperature : undefined,
          maxOutputTokens:
            typeof params.maxOutputTokens === "number" ? params.maxOutputTokens : undefined,
        });

        const outputs: CellOutput[] = [];
        for await (const ev of stream) {
          if (ev.kind === "delta") {
            outputs.push({ kind: "stream", content: ev.text });
          } else if (ev.kind === "done") {
            if (ev.stopReason === "error") {
              outputs.push({ kind: "error", message: ev.errorMessage ?? "llm error" });
            } else {
              outputs.push({
                kind: "text",
                content: ev.finalText,
                mime_type: "text/plain",
              });
            }
          }
        }
        return { outputs };
      }

      if (lang === "candle-inference") {
        // P4.1: scaffold dispatch. Today the smoke-test path proves
        // Candle is alive in the WASM bundle. Real model loading goes
        // through @workbook/runtime/modelArtifactResolver and lands as
        // P4.1+ work — for now this confirms the dispatcher is wired.
        if (!wasm.candleSmokeTest) {
          throw new Error("runtime built without candle feature");
        }
        const outputs = wasm.candleSmokeTest();
        return { outputs };
      }

      if (lang === "linfa-train") {
        // P4.4: scaffold dispatch. Smoke-test path fits a 1-feature
        // linear regression to prove Linfa is alive. Real dataset-driven
        // training (with the workbook data layer) lands incrementally.
        if (!wasm.linfaSmokeTest) {
          throw new Error("runtime built without linfa feature");
        }
        const outputs = wasm.linfaSmokeTest();
        return { outputs };
      }

      throw new Error(`unsupported cell language: ${lang}`);
    },

    async pauseRuntime(runtimeId) {
      const wasm = await ensureWasm();
      wasm.pauseRuntime?.({ runtime_id: runtimeId });
    },

    async destroyRuntime(runtimeId) {
      const wasm = await ensureWasm();
      wasm.destroyRuntime?.({ runtime_id: runtimeId });
      if (sqlite) {
        sqlite.dispose();
        sqlite = null;
      }
    },

    async buildInfo() {
      const wasm = await ensureWasm();
      return wasm.build_info();
    },

    async registerMemory(id, bytes) {
      // First write wins — overwriting an existing memory id at
      // mount time is suspicious. appendMemory is the right path
      // for incremental writes.
      if (memoryBuffers.has(id)) {
        throw new Error(`memory id already registered: ${id}`);
      }
      memoryBuffers.set(id, bytes);
    },

    async appendMemory(id, rows) {
      const existing = memoryBuffers.get(id);
      if (!existing) {
        throw new Error(`memory id not registered: ${id}`);
      }
      // Prefer the Rust-side appendArrowIpc binding (proper schema
      // check + single-header concat). Falls back to naive byte
      // concat with a clear warning when the binding isn't present
      // — broken past the first append, but non-fatal so first ship
      // works on stale runtime bundles.
      const wasm = await ensureWasm();
      let combined: Uint8Array;
      if (wasm.appendArrowIpc) {
        combined = wasm.appendArrowIpc(existing, rows);
      } else {
        console.warn(
          "appendMemory: runtime-wasm missing appendArrowIpc binding — " +
            "falling back to naive concatenation, which truncates at the " +
            "first EOS marker on subsequent appends. Rebuild runtime-wasm.",
        );
        combined = new Uint8Array(existing.byteLength + rows.byteLength);
        combined.set(existing, 0);
        combined.set(rows, existing.byteLength);
      }
      memoryBuffers.set(id, combined);
      const sha256 = await sha256HexFromBytes(combined);
      return { sha256, bytes: combined.byteLength };
    },

    async exportMemory(id) {
      const bytes = memoryBuffers.get(id);
      if (!bytes) throw new Error(`memory id not registered: ${id}`);
      return bytes;
    },

    async registerDoc(id, handle) {
      if (docHandles.has(id)) {
        throw new Error(`doc id already registered: ${id}`);
      }
      docHandles.set(id, handle);
    },

    async docMutate(id, ops) {
      const handle = docHandles.get(id);
      if (!handle) {
        throw new Error(`doc id not registered: ${id}`);
      }
      const snapshot = handle.mutate(ops);
      const sha256 = await sha256HexFromBytes(snapshot);
      return { sha256, bytes: snapshot.byteLength, snapshot };
    },

    async exportDoc(id) {
      const handle = docHandles.get(id);
      if (!handle) throw new Error(`doc id not registered: ${id}`);
      return handle.exportSnapshot();
    },

    async readDoc(id) {
      const handle = docHandles.get(id);
      if (!handle) throw new Error(`doc id not registered: ${id}`);
      return handle.toJSON();
    },

    getDocHandle(id) {
      // Synchronous handle lookup for the SDK's useDoc() hook. Authors
      // call Loro's mutation API directly on the returned handle;
      // changes round-trip back into the .workbook.html file via the
      // save handler's exportDoc() call on Cmd+S.
      return docHandles.get(id);
    },

    listDocIds() {
      // Surfaces the registered ids for the wb.* storage SDK's
      // default-doc resolution. Returns iteration order matching
      // registerDoc() call order.
      return Array.from(docHandles.keys());
    },
  };
}

/** SHA-256 hex of a byte buffer. Lifted from modelArtifactResolver
 *  to avoid a circular import. */
async function sha256HexFromBytes(bytes: Uint8Array): Promise<string> {
  const digest = await crypto.subtle.digest("SHA-256", bytes as BufferSource);
  return [...new Uint8Array(digest)]
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}
